/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SzConfigManager {
  /** Creates a new configuration from the default template and exports it as JSON. */
  createConfig(): string
  /** Creates a configuration from a registered configuration ID and exports it as JSON. */
  createConfigFromId(configId: number): string
  /** Creates a configuration from a JSON definition string and exports it as JSON. */
  createConfigFromDefinition(configDefinition: string): string
  /** Gets information about all registered configuration versions as a JSON string. */
  getConfigRegistry(): string
  /** Gets the currently active default configuration ID. */
  getDefaultConfigId(): number
  /** Registers a new configuration version and returns the assigned configuration ID. */
  registerConfig(configDefinition: string, configComment?: string | undefined | null): number
  /** Atomically replaces the default configuration ID (optimistic locking). */
  replaceDefaultConfigId(currentDefaultConfigId: number, newDefaultConfigId: number): void
  /** Registers and activates a configuration in one operation, returning the assigned ID. */
  setDefaultConfig(configDefinition: string, configComment?: string | undefined | null): number
  /** Sets the active configuration by ID. */
  setDefaultConfigId(configId: number): void
}
export type SzConfigManagerWrapper = SzConfigManager

export declare class SzDiagnostic {
  /**
   * Runs a performance benchmark on the repository for the specified duration.
   *
   * Returns a JSON string with performance metrics including operations per second.
   */
  checkRepositoryPerformance(secondsToRun: number): string
  /**
   * Gets detailed information about a specific feature by its internal ID.
   *
   * Returns a JSON string with feature details including type, value, and usage statistics.
   */
  getFeature(featureId: number): string
  /** Gets repository statistics and information as a JSON string. */
  getRepositoryInfo(): string
  /**
   * Purges all entity data from the repository while preserving configuration.
   *
   * Warning: This permanently deletes all entity resolution data.
   */
  purgeRepository(): void
}
export type SzDiagnosticWrapper = SzDiagnostic

export declare class SzEngine {
  /** Primes the engine for optimal performance by loading internal caches. */
  primeEngine(): void
  /** Gets engine performance statistics as a JSON string. */
  getStats(): string
  /**
   * Adds a record for entity resolution.
   *
   * Inserts or updates a record in the entity repository.
   */
  addRecord(dataSourceCode: string, recordId: string, recordDefinition: string, flags?: bigint | undefined | null): string
  /** Deletes a record from the entity repository. */
  deleteRecord(dataSourceCode: string, recordId: string, flags?: bigint | undefined | null): string
  /** Reevaluates a specific record against current resolution rules. */
  reevaluateRecord(dataSourceCode: string, recordId: string, flags?: bigint | undefined | null): string
  /** Reevaluates all records for a specific entity. */
  reevaluateEntity(entityId: number, flags?: bigint | undefined | null): string
  /** Gets record information by data source and record ID. */
  getRecord(dataSourceCode: string, recordId: string, flags?: bigint | undefined | null): string
  /** Gets a preview of how a record would be processed without persisting it. */
  getRecordPreview(recordDefinition: string, flags?: bigint | undefined | null): string
  /** Gets entity information by entity ID. */
  getEntityById(entityId: number, flags?: bigint | undefined | null): string
  /** Gets entity information by record key (data source + record ID). */
  getEntityByRecord(dataSourceCode: string, recordId: string, flags?: bigint | undefined | null): string
  /** Searches for entities by attributes. */
  searchByAttributes(attributes: string, searchProfile?: string | undefined | null, flags?: bigint | undefined | null): string
  /** Analyzes why a search result was returned for an entity. */
  whySearch(attributes: string, entityId: number, searchProfile?: string | undefined | null, flags?: bigint | undefined | null): string
  /** Analyzes why two entities are related. */
  whyEntities(entityId1: number, entityId2: number, flags?: bigint | undefined | null): string
  /** Analyzes why two records resolved together. */
  whyRecords(dsCode1: string, recId1: string, dsCode2: string, recId2: string, flags?: bigint | undefined | null): string
  /** Analyzes why a record belongs to its current entity. */
  whyRecordInEntity(dataSourceCode: string, recordId: string, flags?: bigint | undefined | null): string
  /** Analyzes how an entity was constructed step by step. */
  howEntity(entityId: number, flags?: bigint | undefined | null): string
  /** Creates a virtual entity from record keys without persisting. */
  getVirtualEntity(recordKeys: Array<RecordKey>, flags?: bigint | undefined | null): string
  /** Finds interesting entities related to a given entity by entity ID. */
  findInterestingEntitiesById(entityId: number, flags?: bigint | undefined | null): string
  /** Finds interesting entities related to a given entity by record key. */
  findInterestingEntitiesByRecord(dataSourceCode: string, recordId: string, flags?: bigint | undefined | null): string
  /** Finds a relationship path between two entities. */
  findPath(startEntityId: number, endEntityId: number, maxDegrees: number, avoidEntityIds?: Array<number> | undefined | null, requiredDataSources?: Array<string> | undefined | null, flags?: bigint | undefined | null): string
  /** Finds a network of related entities starting from seed entity IDs. */
  findNetwork(entityIds: Array<number>, maxDegrees: number, buildOutDegree: number, maxEntities: number, flags?: bigint | undefined | null): string
  /** Gets the next pending redo record from the queue. */
  getRedoRecord(): string
  /** Counts pending redo records in the queue. */
  countRedoRecords(): number
  /** Processes a redo record for deferred resolution. */
  processRedoRecord(redoRecord: string, flags?: bigint | undefined | null): string
  /** Starts a JSON entity export. Returns an export handle. */
  exportJsonEntityReport(flags?: bigint | undefined | null): number
  /** Starts a CSV entity export. Returns an export handle. */
  exportCsvEntityReport(csvColumnList: string, flags?: bigint | undefined | null): number
  /** Fetches the next batch of export data. Returns empty string when complete. */
  fetchNext(exportHandle: number): string
  /** Closes an export operation and releases resources. */
  closeExport(exportHandle: number): void
}
export type SzEngineWrapper = SzEngine

export declare class SzEnvironment {
  /**
   * Creates a new SzEnvironment instance.
   *
   * Uses the singleton pattern via `SzEnvironmentCore::get_instance()`.
   */
  constructor(moduleName: string, settings: string, verboseLogging?: boolean | undefined | null)
  /** Checks if the environment has been destroyed. */
  isDestroyed(): boolean
  /**
   * Destroys the environment and releases native resources.
   *
   * After calling destroy, this wrapper is no longer usable.
   */
  destroy(): void
  /** Reinitializes the environment with a different configuration. */
  reinitialize(configId: number): void
  /** Gets the currently active configuration ID. */
  getActiveConfigId(): number
  /** Gets the engine interface for entity resolution operations. */
  getEngine(): SzEngine
  /** Gets the configuration manager interface. */
  getConfigManager(): SzConfigManager
  /** Gets the diagnostic interface for system monitoring. */
  getDiagnostic(): SzDiagnostic
  /** Gets the product interface for version and license information. */
  getProduct(): SzProductWrapper
}
export type SzEnvironmentWrapper = SzEnvironment

export declare class SzProduct {
  /** Gets the product license details as a JSON string. */
  getLicense(): string
  /** Gets the product version information as a JSON string. */
  getVersion(): string
}
export type SzProductWrapper = SzProduct

/** Returns the version of the NAPI bridge itself. */
export declare function bridgeVersion(): string

/** A single flag entry with name and u64 value. */
export interface FlagEntry {
  name: string
  value: bigint
}

/**
 * Returns all SzFlags as name-value pairs.
 *
 * The JS wrapper uses this to build the frozen `SzFlags` export object.
 * Values are BigInt to correctly represent all 64-bit flag values including
 * WITH_INFO at bit 62.
 */
export declare function getAllFlags(): Array<FlagEntry>

/**
 * A record key identifying a specific record by data source and record ID.
 * Used by `getVirtualEntity` to specify which records to combine.
 */
export interface RecordKey {
  dataSourceCode: string
  recordId: string
}
