/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function addAttribute(configJson: string, options: AddAttributeOptions): string

export interface AddAttributeOptions {
  attribute: string
  feature: string
  element: string
  class: string
  defaultValue?: string
  internal?: string
  required?: string
}

export declare function addBehaviorOverride(configJson: string, featureCode: string, usageType: string, behavior: string): string

export declare function addCandidateFunction(configJson: string, rtypeCode: string, candidateFunc: string): string

export declare function addComparisonCall(configJson: string, options: AddComparisonCallOptions): string

export declare function addComparisonCallElement(configJson: string, options: AddComparisonCallElementOptions): string

export interface AddComparisonCallElementOptions {
  cfcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
}

export interface AddComparisonCallOptions {
  ftypeCode: string
  cfuncCode: string
  elementList: Array<string>
}

export declare function addComparisonFuncReturnCode(configJson: string, cfuncCode: string, cfrtnCode: string, cfrtnDesc?: string | undefined | null): string

export declare function addComparisonFunction(configJson: string, cfuncCode: string, options: AddComparisonFunctionOptions): string

export interface AddComparisonFunctionOptions {
  connectStr: string
  description?: string
  language?: string
  anonSupport?: string
}

export declare function addComparisonThreshold(configJson: string, options: AddComparisonThresholdOptions): string

export interface AddComparisonThresholdOptions {
  cfuncCode?: string
  ftypeCode?: string
  cfuncRtnval?: string
  execOrder?: number
  sameScore?: number
  closeScore?: number
  likelyScore?: number
  plausibleScore?: number
  unLikelyScore?: number
}

export declare function addConfigSection(configJson: string, sectionName: string): string

export declare function addConfigSectionField(configJson: string, sectionName: string, fieldName: string, fieldValue: string): string

export declare function addDataSource(configJson: string, options: AddDataSourceOptions): string

export interface AddDataSourceOptions {
  code: string
  retentionLevel?: string
  conversational?: string
  reliability?: number
}

export declare function addDistinctCall(configJson: string, options: AddDistinctCallOptions): string

export declare function addDistinctCallElement(configJson: string, options: AddDistinctCallElementOptions): string

export interface AddDistinctCallElementOptions {
  dfcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
}

export interface AddDistinctCallOptions {
  ftypeCode: string
  dfuncCode: string
  elementList: Array<string>
}

export declare function addDistinctFunction(configJson: string, dfuncCode: string, options: AddDistinctFunctionOptions): string

export interface AddDistinctFunctionOptions {
  connectStr: string
  description?: string
  language?: string
}

export declare function addElement(configJson: string, options: AddElementOptions): string

export interface AddElementOptions {
  code: string
  description?: string
  dataType?: string
  tokenized?: string
}

export declare function addExpressionCall(configJson: string, options: AddExpressionCallOptions): string

export declare function addExpressionCallElement(configJson: string, options: AddExpressionCallElementOptions): string

export interface AddExpressionCallElementOptions {
  efcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
  felemReq: string
}

export interface AddExpressionCallOptions {
  efuncCode: string
  elementList: Array<ExpressionCallElementListItem>
  ftypeCode?: string
  felemCode?: string
  execOrder?: number
  expressionFeature?: string
  isVirtual?: string
}

export declare function addExpressionFunction(configJson: string, efuncCode: string, options: AddExpressionFunctionOptions): string

export interface AddExpressionFunctionOptions {
  connectStr: string
  description?: string
  language?: string
}

export declare function addFeature(configJson: string, options: AddFeatureOptions): string

export declare function addFeatureComparison(configJson: string, options: AddFeatureComparisonOptions): string

export declare function addFeatureComparisonElement(configJson: string, options: AddFeatureComparisonOptions): string

export interface AddFeatureComparisonOptions {
  featureCode: string
  elementCode: string
  execOrder?: number
  displayLevel?: number
  displayDelim?: string
  derived?: string
}

export declare function addFeatureDistinctCallElement(configJson: string, options: AddFeatureDistinctCallElementOptions): string

export interface AddFeatureDistinctCallElementOptions {
  featureCode: string
  distinctFuncCode: string
  elementCode?: string
  execOrder?: number
}

export interface AddFeatureOptions {
  feature: string
  elementList: string
  class?: string
  behavior?: string
  candidates?: string
  anonymize?: string
  derived?: string
  history?: string
  matchkey?: string
  standardize?: string
  expression?: string
  comparison?: string
  version?: number
  rtypeId?: number
}

export declare function addFragment(configJson: string, fragmentConfig: string): string

export declare function addGenericThreshold(configJson: string, options: AddGenericThresholdOptions): string

export interface AddGenericThresholdOptions {
  plan?: string
  behavior?: string
  scoringCap?: number
  candidateCap?: number
  sendToRedo?: string
  feature?: string
}

export declare function addMatchingFunction(configJson: string, rtypeCode: string, matchingFunc: string): string

export declare function addRule(configJson: string, id: number, ruleConfig: string): string

export declare function addScoringFunction(configJson: string, rtypeCode: string, scoringFunc: string): string

export declare function addStandardizeCall(configJson: string, options: AddStandardizeCallOptions): string

export declare function addStandardizeCallElement(configJson: string, options: AddStandardizeCallElementOptions): string

export interface AddStandardizeCallElementOptions {
  ftypeId: number
  sfuncId: number
  felemId?: number
  execOrder?: number
}

export interface AddStandardizeCallOptions {
  sfuncCode: string
  ftypeCode?: string
  felemCode?: string
  execOrder?: number
}

export declare function addStandardizeFunction(configJson: string, sfuncCode: string, options: AddStandardizeFunctionOptions): string

export interface AddStandardizeFunctionOptions {
  connectStr: string
  description?: string
  language?: string
}

export declare function addToNameHash(configJson: string, name: string): string

export declare function addToSsnLast4Hash(configJson: string, name: string): string

export declare function addValidationFunction(configJson: string, attrCode: string, validationFunc: string): string

/** Returns the version of the NAPI configtool bridge. */
export declare function bridgeVersion(): string

export declare function cloneGenericPlan(configJson: string, sourceGplanCode: string, newGplanCode: string, newGplanDesc?: string | undefined | null): string

export declare function deleteAttribute(configJson: string, code: string): string

export declare function deleteBehaviorOverride(configJson: string, featureCode: string, usageType: string): string

export declare function deleteCandidateFunction(configJson: string, rtypeCode: string): string

export declare function deleteComparisonCall(configJson: string, cfcallId: number): string

export declare function deleteComparisonCallElement(configJson: string, options: DeleteComparisonCallElementOptions): string

export interface DeleteComparisonCallElementOptions {
  cfcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
}

export declare function deleteComparisonFunction(configJson: string, cfuncCode: string): string

export declare function deleteComparisonThreshold(configJson: string, cfuncCode: string, ftypeCode: string): string

export declare function deleteDataSource(configJson: string, code: string): string

export declare function deleteDistinctCall(configJson: string, dfcallId: number): string

export declare function deleteDistinctCallElement(configJson: string, options: DeleteDistinctCallElementOptions): string

export interface DeleteDistinctCallElementOptions {
  dfcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
}

export declare function deleteDistinctFunction(configJson: string, dfuncCode: string): string

export declare function deleteElement(configJson: string, code: string): string

export declare function deleteExpressionCall(configJson: string, efcallId: number): string

export declare function deleteExpressionCallElement(configJson: string, options: DeleteExpressionCallElementOptions): string

export interface DeleteExpressionCallElementOptions {
  efcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
}

export declare function deleteExpressionFunction(configJson: string, efuncCode: string): string

export declare function deleteFeature(configJson: string, featureCodeOrId: string): string

export declare function deleteFeatureComparison(configJson: string, featureCode: string, elementCode: string): string

export declare function deleteFeatureComparisonElement(configJson: string, featureCode: string, elementCode: string): string

export declare function deleteFragment(configJson: string, fragmentCode: string): string

export declare function deleteFromNameHash(configJson: string, name: string): string

export declare function deleteFromSsnLast4Hash(configJson: string, name: string): string

export declare function deleteGenericPlan(configJson: string, gplanCode: string): string

export declare function deleteGenericThreshold(configJson: string, options: DeleteGenericThresholdOptions): string

export interface DeleteGenericThresholdOptions {
  plan?: string
  behavior?: string
  feature?: string
}

export declare function deleteMatchingFunction(configJson: string, rtypeCode: string): string

export declare function deleteRule(configJson: string, ruleCode: string): string

export declare function deleteScoringFunction(configJson: string, rtypeCode: string): string

export declare function deleteStandardizeCall(configJson: string, sfcallId: number): string

export declare function deleteStandardizeCallElement(configJson: string, options: DeleteStandardizeCallElementOptions): string

export interface DeleteStandardizeCallElementOptions {
  ftypeId: number
  sfuncId: number
  felemId?: number
}

export declare function deleteStandardizeFunction(configJson: string, sfuncCode: string): string

export declare function deleteValidationFunction(configJson: string, attrCode: string): string

export interface ExpressionCallElementListItem {
  element: string
  required: string
  feature?: string
}

export declare function getAttribute(configJson: string, code: string): string

export declare function getBehaviorOverride(configJson: string, featureCode: string, usageType: string): string

export declare function getCandidateFunction(configJson: string, rtypeCode: string): string

export declare function getComparisonCall(configJson: string, cfcallId: number): string

export declare function getComparisonFunction(configJson: string, cfuncCode: string): string

export declare function getCompatibilityVersion(configJson: string): string

export declare function getConfigSection(configJson: string, sectionName: string, filter?: string | undefined | null): string

export declare function getDataSource(configJson: string, code: string): string

export declare function getDistinctCall(configJson: string, dfcallId: number): string

export declare function getDistinctFunction(configJson: string, dfuncCode: string): string

export declare function getElement(configJson: string, code: string): string

export declare function getExpressionCall(configJson: string, efcallId: number): string

export declare function getExpressionFunction(configJson: string, efuncCode: string): string

export declare function getFeature(configJson: string, featureCodeOrId: string): string

export declare function getFeatureClass(configJson: string, fclassIdOrCode: string): string

export declare function getFeatureComparison(configJson: string, options: GetFeatureComparisonOptions): string

export interface GetFeatureComparisonOptions {
  featureCode: string
  elementCode: string
}

export declare function getFragment(configJson: string, codeOrId: string): string

export declare function getMatchingFunction(configJson: string, rtypeCode: string): string

export declare function getRule(configJson: string, codeOrId: string): string

export declare function getScoringFunction(configJson: string, rtypeCode: string): string

export declare function getStandardizeCall(configJson: string, sfcallId: number): string

export declare function getStandardizeFunction(configJson: string, sfuncCode: string): string

export declare function getThreshold(configJson: string, thresholdId: number): string

export declare function getValidationFunction(configJson: string, attrCode: string): string

export declare function getVersion(configJson: string): string

export declare function listAttributes(configJson: string): string

export declare function listBehaviorOverrides(configJson: string): string

export declare function listCandidateFunctions(configJson: string): string

export declare function listComparisonCalls(configJson: string): string

export declare function listComparisonFunctions(configJson: string): string

export declare function listComparisonThresholds(configJson: string): string

export declare function listConfigSections(configJson: string): string

export declare function listDataSources(configJson: string): string

export declare function listDistinctCalls(configJson: string): string

export declare function listDistinctFunctions(configJson: string): string

export declare function listElements(configJson: string): string

export declare function listExpressionCalls(configJson: string): string

export declare function listExpressionFunctions(configJson: string): string

export declare function listFeatureClasses(configJson: string): string

export declare function listFeatureComparisons(configJson: string): string

export declare function listFeatures(configJson: string): string

export declare function listFragments(configJson: string): string

export declare function listGenericPlans(configJson: string, filter?: string | undefined | null): string

export declare function listGenericThresholds(configJson: string): string

export declare function listMatchingFunctions(configJson: string): string

export declare function listRules(configJson: string): string

export declare function listScoringFunctions(configJson: string): string

export declare function listStandardizeCalls(configJson: string): string

export declare function listStandardizeFunctions(configJson: string): string

export declare function listSystemParameters(configJson: string): string

export declare function listValidationFunctions(configJson: string): string

export declare function processFile(configJson: string, filePath: string): string

export declare function processScript(configJson: string, script: string): string

export declare function removeCandidateFunction(configJson: string, rtypeCode: string): string

export declare function removeConfigSection(configJson: string, sectionName: string): string

export declare function removeConfigSectionField(configJson: string, sectionName: string, fieldName: string): string

export declare function removeMatchingFunction(configJson: string, rtypeCode: string): string

export declare function removeScoringFunction(configJson: string, rtypeCode: string): string

export declare function removeValidationFunction(configJson: string, attrCode: string): string

export declare function setAttribute(configJson: string, options: SetAttributeOptions): string

export interface SetAttributeOptions {
  attribute: string
  internal?: string
  required?: string
  defaultValue?: string
}

export declare function setCandidateFunction(configJson: string, rtypeCode: string, candidateFunc?: string | undefined | null): string

export declare function setComparisonCall(configJson: string, options: SetComparisonCallOptions): string

export declare function setComparisonCallElement(configJson: string, options: SetComparisonCallElementOptions): string

export interface SetComparisonCallElementOptions {
  cfcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
  updates: string
}

export interface SetComparisonCallOptions {
  cfcallId: number
  execOrder?: number
}

export declare function setComparisonFunction(configJson: string, cfuncCode: string, options: SetComparisonFunctionOptions): string

export interface SetComparisonFunctionOptions {
  connectStr?: string
  description?: string
  language?: string
  anonSupport?: string
}

export declare function setComparisonThreshold(configJson: string, options: SetComparisonThresholdOptions): string

export interface SetComparisonThresholdOptions {
  cfuncCode?: string
  ftypeCode?: string
  cfuncRtnval?: string
  execOrder?: number
  sameScore?: number
  closeScore?: number
  likelyScore?: number
  plausibleScore?: number
  unLikelyScore?: number
}

export declare function setDataSource(configJson: string, code: string, options: SetDataSourceOptions): string

export interface SetDataSourceOptions {
  retentionLevel?: string
  conversational?: string
  reliability?: number
}

export declare function setDistinctCall(configJson: string, options: SetDistinctCallOptions): string

export declare function setDistinctCallElement(configJson: string, options: SetDistinctCallElementOptions): string

export interface SetDistinctCallElementOptions {
  dfcallId: number
  ftypeId: number
  felemId: number
  execOrder: number
  updates: string
}

export interface SetDistinctCallOptions {
  dfcallId: number
  execOrder?: number
}

export declare function setDistinctFunction(configJson: string, dfuncCode: string, options: SetDistinctFunctionOptions): string

export interface SetDistinctFunctionOptions {
  connectStr?: string
  description?: string
  language?: string
}

export declare function setElement(configJson: string, options: SetElementOptions): string

export interface SetElementOptions {
  code: string
  description?: string
  dataType?: string
  tokenized?: string
}

export declare function setExpressionCall(configJson: string, options: SetExpressionCallOptions): string

export declare function setExpressionCallElement(configJson: string, options: SetExpressionCallElementOptions): string

export interface SetExpressionCallElementOptions {
  ftypeId: number
  felemId: number
  execOrder: number
  felemReq: string
}

export interface SetExpressionCallOptions {
  efcallId: number
  execOrder?: number
}

export declare function setExpressionFunction(configJson: string, efuncCode: string, options: SetExpressionFunctionOptions): string

export interface SetExpressionFunctionOptions {
  connectStr?: string
  description?: string
  language?: string
}

export declare function setFeature(configJson: string, options: SetFeatureOptions): string

export declare function setFeatureElement(configJson: string, options: SetFeatureElementOptions): string

export declare function setFeatureElementDerived(configJson: string, featureCode: string, elementCode: string, derived: string): string

export declare function setFeatureElementDisplayLevel(configJson: string, featureCode: string, elementCode: string, displayLevel: number): string

export interface SetFeatureElementOptions {
  featureCode: string
  elementCode: string
  execOrder?: number
  displayLevel?: number
  displayDelim?: string
  derived?: string
}

export interface SetFeatureOptions {
  feature: string
  candidates?: string
  anonymize?: string
  derived?: string
  history?: string
  matchkey?: string
  behavior?: string
  class?: string
  version?: number
  rtypeId?: number
}

export declare function setFragment(configJson: string, fragmentCode: string, fragmentConfig: string): string

export declare function setGenericPlan(configJson: string, gplanCode: string, gplanDesc: string): string

export declare function setGenericThreshold(configJson: string, options: SetGenericThresholdOptions): string

export interface SetGenericThresholdOptions {
  plan?: string
  behavior?: string
  feature?: string
  candidateCap?: number
  scoringCap?: number
  sendToRedo?: string
}

export declare function setMatchingFunction(configJson: string, rtypeCode: string, matchingFunc?: string | undefined | null): string

export declare function setRule(configJson: string, options: SetRuleOptions): string

export interface SetRuleOptions {
  code: string
  resolve?: string
  relate?: string
  rtypeId?: number
  fragment?: string
  disqualifier?: string
  tier?: number
}

export declare function setScoringFunction(configJson: string, rtypeCode: string, scoringFunc?: string | undefined | null): string

export declare function setStandardizeCall(configJson: string, options: SetStandardizeCallOptions): string

export declare function setStandardizeCallElement(configJson: string, options: SetStandardizeCallElementOptions): string

export interface SetStandardizeCallElementOptions {
  ftypeId: number
  sfuncId: number
  felemId?: number
  updates: string
}

export interface SetStandardizeCallOptions {
  sfcallId: number
  execOrder?: number
}

export declare function setStandardizeFunction(configJson: string, sfuncCode: string, options: SetStandardizeFunctionOptions): string

export interface SetStandardizeFunctionOptions {
  connectStr?: string
  description?: string
  language?: string
}

export declare function setSystemParameter(configJson: string, parameterName: string, parameterValue: string): string

export declare function setThreshold(configJson: string, thresholdId: number): string

export declare function setValidationFunction(configJson: string, attrCode: string, validationFunc?: string | undefined | null): string

export declare function updateCompatibilityVersion(configJson: string, newVersion: string): string

export declare function updateFeatureVersion(configJson: string, version: string): string

export declare function verifyCompatibilityVersion(configJson: string, expectedVersion: string): VerifyCompatibilityVersionResult

export interface VerifyCompatibilityVersionResult {
  currentVersion: string
  matches: boolean
}
