// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./senzing-configtool.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-android-arm64')
        const bindingPackageVersion = require('@senzing/configtool-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./senzing-configtool.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-android-arm-eabi')
        const bindingPackageVersion = require('@senzing/configtool-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./senzing-configtool.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-win32-x64-gnu')
        const bindingPackageVersion = require('@senzing/configtool-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./senzing-configtool.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-win32-x64-msvc')
        const bindingPackageVersion = require('@senzing/configtool-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./senzing-configtool.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-win32-ia32-msvc')
        const bindingPackageVersion = require('@senzing/configtool-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./senzing-configtool.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-win32-arm64-msvc')
        const bindingPackageVersion = require('@senzing/configtool-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./senzing-configtool.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@senzing/configtool-darwin-universal')
      const bindingPackageVersion = require('@senzing/configtool-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./senzing-configtool.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-darwin-x64')
        const bindingPackageVersion = require('@senzing/configtool-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./senzing-configtool.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-darwin-arm64')
        const bindingPackageVersion = require('@senzing/configtool-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./senzing-configtool.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-freebsd-x64')
        const bindingPackageVersion = require('@senzing/configtool-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./senzing-configtool.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-freebsd-arm64')
        const bindingPackageVersion = require('@senzing/configtool-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./senzing-configtool.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-x64-musl')
          const bindingPackageVersion = require('@senzing/configtool-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./senzing-configtool.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-x64-gnu')
          const bindingPackageVersion = require('@senzing/configtool-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./senzing-configtool.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-arm64-musl')
          const bindingPackageVersion = require('@senzing/configtool-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./senzing-configtool.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-arm64-gnu')
          const bindingPackageVersion = require('@senzing/configtool-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./senzing-configtool.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-arm-musleabihf')
          const bindingPackageVersion = require('@senzing/configtool-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./senzing-configtool.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@senzing/configtool-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./senzing-configtool.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-loong64-musl')
          const bindingPackageVersion = require('@senzing/configtool-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./senzing-configtool.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-loong64-gnu')
          const bindingPackageVersion = require('@senzing/configtool-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./senzing-configtool.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-riscv64-musl')
          const bindingPackageVersion = require('@senzing/configtool-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./senzing-configtool.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@senzing/configtool-linux-riscv64-gnu')
          const bindingPackageVersion = require('@senzing/configtool-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./senzing-configtool.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-linux-ppc64-gnu')
        const bindingPackageVersion = require('@senzing/configtool-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./senzing-configtool.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-linux-s390x-gnu')
        const bindingPackageVersion = require('@senzing/configtool-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./senzing-configtool.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-openharmony-arm64')
        const bindingPackageVersion = require('@senzing/configtool-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./senzing-configtool.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-openharmony-x64')
        const bindingPackageVersion = require('@senzing/configtool-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./senzing-configtool.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@senzing/configtool-openharmony-arm')
        const bindingPackageVersion = require('@senzing/configtool-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./senzing-configtool.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@senzing/configtool-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.addAttribute = nativeBinding.addAttribute
module.exports.addBehaviorOverride = nativeBinding.addBehaviorOverride
module.exports.addCandidateFunction = nativeBinding.addCandidateFunction
module.exports.addComparisonCall = nativeBinding.addComparisonCall
module.exports.addComparisonCallElement = nativeBinding.addComparisonCallElement
module.exports.addComparisonFuncReturnCode = nativeBinding.addComparisonFuncReturnCode
module.exports.addComparisonFunction = nativeBinding.addComparisonFunction
module.exports.addComparisonThreshold = nativeBinding.addComparisonThreshold
module.exports.addConfigSection = nativeBinding.addConfigSection
module.exports.addConfigSectionField = nativeBinding.addConfigSectionField
module.exports.addDataSource = nativeBinding.addDataSource
module.exports.addDistinctCall = nativeBinding.addDistinctCall
module.exports.addDistinctCallElement = nativeBinding.addDistinctCallElement
module.exports.addDistinctFunction = nativeBinding.addDistinctFunction
module.exports.addElement = nativeBinding.addElement
module.exports.addExpressionCall = nativeBinding.addExpressionCall
module.exports.addExpressionCallElement = nativeBinding.addExpressionCallElement
module.exports.addExpressionFunction = nativeBinding.addExpressionFunction
module.exports.addFeature = nativeBinding.addFeature
module.exports.addFeatureComparison = nativeBinding.addFeatureComparison
module.exports.addFeatureComparisonElement = nativeBinding.addFeatureComparisonElement
module.exports.addFeatureDistinctCallElement = nativeBinding.addFeatureDistinctCallElement
module.exports.addFragment = nativeBinding.addFragment
module.exports.addGenericThreshold = nativeBinding.addGenericThreshold
module.exports.addMatchingFunction = nativeBinding.addMatchingFunction
module.exports.addRule = nativeBinding.addRule
module.exports.addScoringFunction = nativeBinding.addScoringFunction
module.exports.addStandardizeCall = nativeBinding.addStandardizeCall
module.exports.addStandardizeCallElement = nativeBinding.addStandardizeCallElement
module.exports.addStandardizeFunction = nativeBinding.addStandardizeFunction
module.exports.addToNameHash = nativeBinding.addToNameHash
module.exports.addToSsnLast4Hash = nativeBinding.addToSsnLast4Hash
module.exports.addValidationFunction = nativeBinding.addValidationFunction
module.exports.bridgeVersion = nativeBinding.bridgeVersion
module.exports.cloneGenericPlan = nativeBinding.cloneGenericPlan
module.exports.deleteAttribute = nativeBinding.deleteAttribute
module.exports.deleteBehaviorOverride = nativeBinding.deleteBehaviorOverride
module.exports.deleteCandidateFunction = nativeBinding.deleteCandidateFunction
module.exports.deleteComparisonCall = nativeBinding.deleteComparisonCall
module.exports.deleteComparisonCallElement = nativeBinding.deleteComparisonCallElement
module.exports.deleteComparisonFunction = nativeBinding.deleteComparisonFunction
module.exports.deleteComparisonThreshold = nativeBinding.deleteComparisonThreshold
module.exports.deleteDataSource = nativeBinding.deleteDataSource
module.exports.deleteDistinctCall = nativeBinding.deleteDistinctCall
module.exports.deleteDistinctCallElement = nativeBinding.deleteDistinctCallElement
module.exports.deleteDistinctFunction = nativeBinding.deleteDistinctFunction
module.exports.deleteElement = nativeBinding.deleteElement
module.exports.deleteExpressionCall = nativeBinding.deleteExpressionCall
module.exports.deleteExpressionCallElement = nativeBinding.deleteExpressionCallElement
module.exports.deleteExpressionFunction = nativeBinding.deleteExpressionFunction
module.exports.deleteFeature = nativeBinding.deleteFeature
module.exports.deleteFeatureComparison = nativeBinding.deleteFeatureComparison
module.exports.deleteFeatureComparisonElement = nativeBinding.deleteFeatureComparisonElement
module.exports.deleteFragment = nativeBinding.deleteFragment
module.exports.deleteFromNameHash = nativeBinding.deleteFromNameHash
module.exports.deleteFromSsnLast4Hash = nativeBinding.deleteFromSsnLast4Hash
module.exports.deleteGenericPlan = nativeBinding.deleteGenericPlan
module.exports.deleteGenericThreshold = nativeBinding.deleteGenericThreshold
module.exports.deleteMatchingFunction = nativeBinding.deleteMatchingFunction
module.exports.deleteRule = nativeBinding.deleteRule
module.exports.deleteScoringFunction = nativeBinding.deleteScoringFunction
module.exports.deleteStandardizeCall = nativeBinding.deleteStandardizeCall
module.exports.deleteStandardizeCallElement = nativeBinding.deleteStandardizeCallElement
module.exports.deleteStandardizeFunction = nativeBinding.deleteStandardizeFunction
module.exports.deleteValidationFunction = nativeBinding.deleteValidationFunction
module.exports.getAttribute = nativeBinding.getAttribute
module.exports.getBehaviorOverride = nativeBinding.getBehaviorOverride
module.exports.getCandidateFunction = nativeBinding.getCandidateFunction
module.exports.getComparisonCall = nativeBinding.getComparisonCall
module.exports.getComparisonFunction = nativeBinding.getComparisonFunction
module.exports.getCompatibilityVersion = nativeBinding.getCompatibilityVersion
module.exports.getConfigSection = nativeBinding.getConfigSection
module.exports.getDataSource = nativeBinding.getDataSource
module.exports.getDistinctCall = nativeBinding.getDistinctCall
module.exports.getDistinctFunction = nativeBinding.getDistinctFunction
module.exports.getElement = nativeBinding.getElement
module.exports.getExpressionCall = nativeBinding.getExpressionCall
module.exports.getExpressionFunction = nativeBinding.getExpressionFunction
module.exports.getFeature = nativeBinding.getFeature
module.exports.getFeatureClass = nativeBinding.getFeatureClass
module.exports.getFeatureComparison = nativeBinding.getFeatureComparison
module.exports.getFragment = nativeBinding.getFragment
module.exports.getMatchingFunction = nativeBinding.getMatchingFunction
module.exports.getRule = nativeBinding.getRule
module.exports.getScoringFunction = nativeBinding.getScoringFunction
module.exports.getStandardizeCall = nativeBinding.getStandardizeCall
module.exports.getStandardizeFunction = nativeBinding.getStandardizeFunction
module.exports.getThreshold = nativeBinding.getThreshold
module.exports.getValidationFunction = nativeBinding.getValidationFunction
module.exports.getVersion = nativeBinding.getVersion
module.exports.listAttributes = nativeBinding.listAttributes
module.exports.listBehaviorOverrides = nativeBinding.listBehaviorOverrides
module.exports.listCandidateFunctions = nativeBinding.listCandidateFunctions
module.exports.listComparisonCalls = nativeBinding.listComparisonCalls
module.exports.listComparisonFunctions = nativeBinding.listComparisonFunctions
module.exports.listComparisonThresholds = nativeBinding.listComparisonThresholds
module.exports.listConfigSections = nativeBinding.listConfigSections
module.exports.listDataSources = nativeBinding.listDataSources
module.exports.listDistinctCalls = nativeBinding.listDistinctCalls
module.exports.listDistinctFunctions = nativeBinding.listDistinctFunctions
module.exports.listElements = nativeBinding.listElements
module.exports.listExpressionCalls = nativeBinding.listExpressionCalls
module.exports.listExpressionFunctions = nativeBinding.listExpressionFunctions
module.exports.listFeatureClasses = nativeBinding.listFeatureClasses
module.exports.listFeatureComparisons = nativeBinding.listFeatureComparisons
module.exports.listFeatures = nativeBinding.listFeatures
module.exports.listFragments = nativeBinding.listFragments
module.exports.listGenericPlans = nativeBinding.listGenericPlans
module.exports.listGenericThresholds = nativeBinding.listGenericThresholds
module.exports.listMatchingFunctions = nativeBinding.listMatchingFunctions
module.exports.listRules = nativeBinding.listRules
module.exports.listScoringFunctions = nativeBinding.listScoringFunctions
module.exports.listStandardizeCalls = nativeBinding.listStandardizeCalls
module.exports.listStandardizeFunctions = nativeBinding.listStandardizeFunctions
module.exports.listSystemParameters = nativeBinding.listSystemParameters
module.exports.listValidationFunctions = nativeBinding.listValidationFunctions
module.exports.processFile = nativeBinding.processFile
module.exports.processScript = nativeBinding.processScript
module.exports.removeCandidateFunction = nativeBinding.removeCandidateFunction
module.exports.removeConfigSection = nativeBinding.removeConfigSection
module.exports.removeConfigSectionField = nativeBinding.removeConfigSectionField
module.exports.removeMatchingFunction = nativeBinding.removeMatchingFunction
module.exports.removeScoringFunction = nativeBinding.removeScoringFunction
module.exports.removeValidationFunction = nativeBinding.removeValidationFunction
module.exports.setAttribute = nativeBinding.setAttribute
module.exports.setCandidateFunction = nativeBinding.setCandidateFunction
module.exports.setComparisonCall = nativeBinding.setComparisonCall
module.exports.setComparisonCallElement = nativeBinding.setComparisonCallElement
module.exports.setComparisonFunction = nativeBinding.setComparisonFunction
module.exports.setComparisonThreshold = nativeBinding.setComparisonThreshold
module.exports.setDataSource = nativeBinding.setDataSource
module.exports.setDistinctCall = nativeBinding.setDistinctCall
module.exports.setDistinctCallElement = nativeBinding.setDistinctCallElement
module.exports.setDistinctFunction = nativeBinding.setDistinctFunction
module.exports.setElement = nativeBinding.setElement
module.exports.setExpressionCall = nativeBinding.setExpressionCall
module.exports.setExpressionCallElement = nativeBinding.setExpressionCallElement
module.exports.setExpressionFunction = nativeBinding.setExpressionFunction
module.exports.setFeature = nativeBinding.setFeature
module.exports.setFeatureElement = nativeBinding.setFeatureElement
module.exports.setFeatureElementDerived = nativeBinding.setFeatureElementDerived
module.exports.setFeatureElementDisplayLevel = nativeBinding.setFeatureElementDisplayLevel
module.exports.setFragment = nativeBinding.setFragment
module.exports.setGenericPlan = nativeBinding.setGenericPlan
module.exports.setGenericThreshold = nativeBinding.setGenericThreshold
module.exports.setMatchingFunction = nativeBinding.setMatchingFunction
module.exports.setRule = nativeBinding.setRule
module.exports.setScoringFunction = nativeBinding.setScoringFunction
module.exports.setStandardizeCall = nativeBinding.setStandardizeCall
module.exports.setStandardizeCallElement = nativeBinding.setStandardizeCallElement
module.exports.setStandardizeFunction = nativeBinding.setStandardizeFunction
module.exports.setSystemParameter = nativeBinding.setSystemParameter
module.exports.setThreshold = nativeBinding.setThreshold
module.exports.setValidationFunction = nativeBinding.setValidationFunction
module.exports.updateCompatibilityVersion = nativeBinding.updateCompatibilityVersion
module.exports.updateFeatureVersion = nativeBinding.updateFeatureVersion
module.exports.verifyCompatibilityVersion = nativeBinding.verifyCompatibilityVersion
